/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.pembelianDAO;
import Model.Detailpembelian;
import Model.Pembelian;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDRE
 */
public class pembelian extends javax.swing.JPanel implements ListSelectionListener {

    /**
     * Creates new form pembelian
     */
    private pembelianDAO daoPembelian;
    private DefaultTableModel dtmPembelian;
    private DefaultTableModel dtmDetail;
    private List<Pembelian> listPembelian;
    private List<Detailpembelian> listDetail;

    int rowPembelian;

    public pembelian() {
        initComponents();
        daoPembelian = new pembelianDAO();
        dtmPembelian = (DefaultTableModel) tablePembelian.getModel();
        dtmDetail = (DefaultTableModel) tableDetail.getModel();
        showAllDataPembelian();
    }

    /*
    ---------
    Start of methods 
     */
    //Untuk menampilkan seluruh data pembelian
    private void showAllDataPembelian() {
        tablePembelian.getSelectionModel().removeListSelectionListener(this);
        listPembelian = daoPembelian.getAllPembelian();
        dtmPembelian.getDataVector().removeAllElements();

        for (Pembelian s : listPembelian) {
            listDetail = daoPembelian.getDetailPembelian(s.getIDOrder());
            int total = 0;
            for (int i = 0; i < listDetail.size(); i++) {
                total += listDetail.get(i).getSubtotal();
            }

            dtmPembelian.addRow(new Object[]{
                s.getIDOrder(),
                s.getIDSupplier(),
                s.getMetodePembayaran(),
                s.getTanggalPembelian(),
                total
            });
        }
        tablePembelian.getSelectionModel().addListSelectionListener(this);
    }

    //Untuk menampilkan data produk yang ada dalam pembelian
    private void showAllPembelianData() {
       
            tableDetail.getSelectionModel().removeListSelectionListener(this);
            listDetail = daoPembelian.getDetailPembelian(listPembelian.get(rowPembelian).getIDOrder());
            dtmDetail.getDataVector().removeAllElements();

            for (Detailpembelian od : listDetail) {
                dtmDetail.addRow(new Object[]{
                    od.getIDOrderDetails(),
                    od.getIDProduk() + " - " + od.getIDProduk().getNamaBarang(),
                    od.getHarga(),
                    od.getJumlah(),
                    od.getPotonganHarga(),
                    od.getSubtotal()
                });
            }
            tableDetail.getSelectionModel().addListSelectionListener(this);
        
    }

    //Untuk menghapus data
    private void deleteData() {
        Pembelian s = new Pembelian();
        s.setIDOrder(listPembelian.get(rowPembelian).getIDOrder());
        s.setIDSupplier(listPembelian.get(rowPembelian).getIDSupplier());
        s.setMetodePembayaran(listPembelian.get(rowPembelian).getMetodePembayaran());
        s.setTanggalPembelian(listPembelian.get(rowPembelian).getTanggalPembelian());

        try {
            daoPembelian.deletePembelian(s);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            showAllDataPembelian();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus!");
        }
    }

    /*
    ---------
    End of methods 
     */
    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() == tablePembelian.getSelectionModel()) {
            rowPembelian = tablePembelian.getSelectedRow();
        }
        showAllPembelianData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablePembelian = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Order Details", "ID Produk", "Harga", "Jumlah", "Potongan Harga", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableDetail);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 688, 119));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 538, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon_bawah.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        tablePembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Order", "ID Supplier", "Metode Pembayaran", "Tanggal Pembelian", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tablePembelian);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 688, 236));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Data Pembelian");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Home h = new Home();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tablePembelian;
    // End of variables declaration//GEN-END:variables

}
