/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.returDAO;
import Model.Detailretur;
import Model.Retur;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDRE
 */
public class retur extends javax.swing.JPanel implements ListSelectionListener {

    /**
     * Creates new form retur
     */
    private returDAO daoRetur;
    private DefaultTableModel dtmRetur;
    private DefaultTableModel dtmDetail;

    private List<Retur> listRetur;
    private List<Detailretur> listDetail;

    int rowRetur;

    public retur() {
        initComponents();
        daoRetur = new returDAO();
        dtmRetur = (DefaultTableModel) tableRetur.getModel();
        dtmDetail = (DefaultTableModel) tableDetail.getModel();
        showAllDataRetur();
    }

    /*
    ---------
    Start of methods 
     */
    //Untuk menampilkan seluruh data retur
    private void showAllDataRetur() {
        tableRetur.getSelectionModel().removeListSelectionListener(this);
        listRetur = daoRetur.getAllRetur();
        dtmRetur.getDataVector().removeAllElements();

        for (Retur s : listRetur) {
            listDetail = daoRetur.getDetailRetur(s.getIDRetur());

            dtmRetur.addRow(new Object[]{
                s.getIDRetur(),
                s.getIDOrder(),
                s.getIDCustomer(),
                s.getIDOrder().getTanggalPembayaran()
            });
        }
        tableRetur.getSelectionModel().addListSelectionListener(this);
    }

    //Untuk menampilkan data produk yang ada dalam retur
    private void showAllReturData() {
        tableDetail.getSelectionModel().removeListSelectionListener(this);
        listDetail = daoRetur.getDetailRetur(listRetur.get(rowRetur).getIDRetur());
        dtmDetail.getDataVector().removeAllElements();

        for (Detailretur od : listDetail) {
            dtmDetail.addRow(new Object[]{
                od.getIDReturDetails(),
                od.getIDProduk(),
                od.getIDProduk().getHarga(),
                od.getKeterangan(),
                od.getDisetujui(),});
        }
        tableDetail.getSelectionModel().addListSelectionListener(this);
    }

    //Untuk menghapus data
    private void deleteData() {
        Retur s = new Retur();
        s.setIDRetur(listRetur.get(rowRetur).getIDRetur());
        s.setIDOrder(listRetur.get(rowRetur).getIDOrder());
        s.setIDCustomer(listRetur.get(rowRetur).getIDCustomer());

        try {
            daoRetur.deleteRetur(s);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            showAllDataRetur();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus!");
        }
    }

    /*
    ---------
    End of methods 
     */
    @Override
    public void valueChanged(ListSelectionEvent e) {
       if (e.getSource() == tableRetur.getSelectionModel()) {
            rowRetur = tableRetur.getSelectedRow();
        }
        showAllReturData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jScrollPane11 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tableRetur = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Retur Details", "ID Produk", "Harga", "Keterangan", "Disetujui?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tableDetail);

        add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 688, 119));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 80, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon("I:\\PBOL\\Tugas Besar\\icon_bawah.png")); // NOI18N
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        tableRetur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Retur", "ID Order", "ID Customer", "Tanggal Pembelian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(tableRetur);

        add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 609, 241));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Retur");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 589, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Home h = new Home();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tableRetur;
    // End of variables declaration//GEN-END:variables

}
